#!/usr/bin/env python3
"""
Dump BLE HID Report Map descriptor from an Amazon Fire TV Remote (or any BLE HID device).

Uses bleak to connect and read the HID Report Map characteristic.
Outputs a C array ready to paste into amazon_remote_desc.h.

Usage:
    pip install bleak
    python3 dump_descriptor.py                    # scan and pick device
    python3 dump_descriptor.py --address AA:BB:CC:DD:EE:FF  # connect directly
    python3 dump_descriptor.py --name "Fire TV"   # scan for name substring
"""

from __future__ import annotations

import argparse
import asyncio
import sys

from bleak import BleakClient, BleakScanner

# Standard BLE UUIDs
HID_SERVICE_UUID = "00001812-0000-1000-8000-00805f9b34fb"
REPORT_MAP_UUID = "00002a4b-0000-1000-8000-00805f9b34fb"
HID_REPORT_UUID = "00002a4d-0000-1000-8000-00805f9b34fb"
HID_INFORMATION_UUID = "00002a4a-0000-1000-8000-00805f9b34fb"


def format_c_array(data: bytes, name: str = "amazon_remote_hid_desc") -> str:
    """Format raw bytes as a C uint8_t array."""
    lines = [
        "#pragma once",
        "#include <cstdint>",
        "",
        f"// Auto-generated by dump_descriptor.py",
        f"// Descriptor length: {len(data)} bytes",
        f"static const uint8_t {name}[] = {{",
    ]

    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"    {hex_str},")

    lines.append("};")
    lines.append(f"static const uint16_t {name}_len = sizeof({name});")
    lines.append("")
    return "\n".join(lines)


def parse_report_ids(descriptor: bytes) -> list[int]:
    """Extract Report IDs from a HID Report descriptor."""
    report_ids = []
    i = 0
    while i < len(descriptor):
        item = descriptor[i]
        tag = item & 0xFC
        size = item & 0x03
        if size == 3:
            size = 4  # size 3 means 4 bytes in HID spec
        if tag == 0x84 and size >= 1 and (i + 1) < len(descriptor):  # Report ID tag
            report_ids.append(descriptor[i + 1])
        i += 1 + size
    return sorted(set(report_ids))


async def scan_and_select(name_filter: str | None = None) -> str | None:
    """Scan for BLE HID devices and let user pick one."""
    print("Scanning for BLE HID devices (10s)...")

    devices = await BleakScanner.discover(timeout=10, return_adv=True)

    hid_devices = []
    for device, adv_data in devices.values():
        is_hid = any(
            HID_SERVICE_UUID in str(uuid).lower()
            for uuid in (adv_data.service_uuids or [])
        )
        name = device.name or adv_data.local_name or "Unknown"

        if name_filter and name_filter.lower() not in name.lower():
            continue

        if is_hid or name_filter:
            hid_devices.append((device, name, adv_data.rssi))

    if not hid_devices:
        # Also show devices that match by appearance (gamepad/remote)
        for device, adv_data in devices.values():
            name = device.name or adv_data.local_name or "Unknown"
            if name_filter and name_filter.lower() in name.lower():
                hid_devices.append((device, name, adv_data.rssi))

    if not hid_devices:
        print("No HID devices found.")
        if not name_filter:
            print("Tip: Make sure the remote is in pairing mode (hold Home for 10s)")
            print("     Or try: python3 dump_descriptor.py --name 'Fire TV'")
        return None

    # Sort by RSSI (strongest first)
    hid_devices.sort(key=lambda x: x[2], reverse=True)

    print(f"\nFound {len(hid_devices)} device(s):\n")
    for i, (device, name, rssi) in enumerate(hid_devices):
        print(f"  [{i}] {name} ({device.address}) RSSI: {rssi} dBm")

    if len(hid_devices) == 1:
        choice = 0
        print(f"\nAuto-selecting: {hid_devices[0][1]}")
    else:
        print()
        try:
            choice = int(input("Select device number: "))
        except (ValueError, EOFError):
            return None

    if 0 <= choice < len(hid_devices):
        return hid_devices[choice][0].address
    return None


async def dump_descriptor(address: str) -> bytes | None:
    """Connect to device and read the HID Report Map descriptor."""
    print(f"\nConnecting to {address}...")
    print("(If this hangs, put the remote in pairing mode again)")

    client = None
    try:
        client = BleakClient(address, timeout=30)
        await client.connect()
        print(f"Connected: {client.is_connected}")

        # On macOS, try to pair/bond so HID service is accessible
        try:
            await client.pair()
            print("Paired successfully")
        except NotImplementedError:
            print("Pairing not supported on this OS backend (normal on macOS)")
        except Exception as e:
            print(f"Pairing note: {e} (continuing anyway...)")

        # Re-discover services after pairing (some devices hide HID until bonded)
        services = client.services

        # Check if HID service exists
        hid_service = None
        for service in services:
            if HID_SERVICE_UUID in str(service.uuid).lower():
                hid_service = service
                break

        if not hid_service:
            print("ERROR: No HID service found on this device.")
            print("\nAvailable services:")
            for service in services:
                print(f"  {service.uuid}: {service.description}")
            return None

        print(f"Found HID service: {hid_service.uuid}")

        # List all HID characteristics
        print("\nHID characteristics:")
        for char in hid_service.characteristics:
            print(
                f"  {char.uuid} [{','.join(char.properties)}] - {char.description}"
            )

        # Read Report Map
        report_map = None
        for char in hid_service.characteristics:
            if REPORT_MAP_UUID in str(char.uuid).lower():
                report_map = await client.read_gatt_char(char)
                break

        if report_map is None:
            print("ERROR: Could not read Report Map characteristic.")
            return None

        print(f"\nReport Map: {len(report_map)} bytes")

        # Parse and show Report IDs
        report_ids = parse_report_ids(report_map)
        if report_ids:
            print(f"Report IDs found: {report_ids}")
        else:
            print("No explicit Report IDs found (single report)")

        # Also try to enumerate report characteristics
        print("\nReport characteristics:")
        for char in hid_service.characteristics:
            if HID_REPORT_UUID in str(char.uuid).lower():
                for desc in char.descriptors:
                    if "2908" in str(desc.uuid):  # Report Reference
                        try:
                            ref = await client.read_gatt_descriptor(desc.handle)
                            if len(ref) >= 2:
                                rid, rtype = ref[0], ref[1]
                                type_names = {1: "Input", 2: "Output", 3: "Feature"}
                                print(
                                    f"  Report ID: {rid}, Type: {type_names.get(rtype, rtype)}"
                                )
                        except Exception as e:
                            print(f"  (could not read descriptor: {e})")

        return bytes(report_map)

    except Exception as e:
        import traceback
        print(f"ERROR: {e}")
        traceback.print_exc()
        return None
    finally:
        if client and client.is_connected:
            await client.disconnect()


async def main():
    parser = argparse.ArgumentParser(
        description="Dump BLE HID Report Map descriptor"
    )
    parser.add_argument("--address", "-a", help="BLE device address (AA:BB:CC:DD:EE:FF)")
    parser.add_argument("--name", "-n", help="Filter scan results by name substring")
    parser.add_argument(
        "--output",
        "-o",
        default="main/amazon_remote_desc.h",
        help="Output header file (default: main/amazon_remote_desc.h)",
    )
    parser.add_argument(
        "--raw", action="store_true", help="Also save raw binary descriptor"
    )

    args = parser.parse_args()

    address = args.address
    if not address:
        address = await scan_and_select(args.name)
        if not address:
            sys.exit(1)

    descriptor = await dump_descriptor(address)
    if descriptor is None:
        sys.exit(1)

    # Print raw hex
    print(f"\nRaw hex ({len(descriptor)} bytes):")
    for i in range(0, len(descriptor), 16):
        chunk = descriptor[i : i + 16]
        hex_str = " ".join(f"{b:02X}" for b in chunk)
        print(f"  {i:04X}: {hex_str}")

    # Generate and write C header
    c_code = format_c_array(descriptor)
    print(f"\n--- C header ---\n{c_code}")

    with open(args.output, "w") as f:
        f.write(c_code)
    print(f"\nWritten to: {args.output}")

    if args.raw:
        raw_path = args.output.replace(".h", ".bin")
        with open(raw_path, "wb") as f:
            f.write(descriptor)
        print(f"Raw binary: {raw_path}")

    report_ids = parse_report_ids(descriptor)
    if len(report_ids) > 1:
        print(f"\n⚠ Multiple Report IDs detected: {report_ids}")
        print("  The pass-through bridge handles this correctly — the descriptor")
        print("  includes all Report IDs and the proxy forwards bytes unchanged.")


if __name__ == "__main__":
    asyncio.run(main())
