name: Build

on: [pull_request]

env:
  IDF_TARGET: 'esp32s3'
  IDF_VERSION: 'v5.5.1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ env.IDF_VERSION }}
        target: ${{ env.IDF_TARGET }}
        path: '.'
