name: Build and Release

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

env:
  IDF_TARGET: 'esp32s3'
  IDF_VERSION: 'v5.5.1'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        remote: [amazon, onn]

    name: Build (${{ matrix.remote }})

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ env.IDF_VERSION }}
        target: ${{ env.IDF_TARGET }}
        path: '.'
        command: >
          idf.py
          -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.defaults.${{ matrix.remote }}"
          build

    - name: Generate merged binary
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ env.IDF_VERSION }}
        target: ${{ env.IDF_TARGET }}
        path: '.'
        command: >
          esptool.py --chip esp32s3 merge_bin
          -o build/atv-hid-bridge-${{ matrix.remote }}.bin
          --flash_mode dio --flash_freq 80m --flash_size 4MB
          0x0 build/bootloader/bootloader.bin
          0x8000 build/partition_table/partition-table.bin
          0x10000 build/esp-usb-ble-hid.bin

    - name: Upload merged binary
      uses: actions/upload-artifact@v4
      with:
        name: atv-hid-bridge-${{ matrix.remote }}
        path: build/atv-hid-bridge-${{ matrix.remote }}.bin

    - name: Attach binary to release
      uses: softprops/action-gh-release@v2
      if: ${{ github.event.release && github.event.action == 'published' }}
      with:
        files: build/atv-hid-bridge-${{ matrix.remote }}.bin
